version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  flask:
    mem_limit: 32212254720
    cpus: 3.8
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code